name: Docker Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'develop'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci --omit=dev

      - name: Build
        run: npm run build

      - name: Set Docker tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAGS=deploy latest" >> $GITHUB_ENV
          else
            echo "TAGS=latest" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Docker login to GHCR
        run: echo "${{ secrets.GHCR }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image (multi-arch)
        run: |
          for TAG in $TAGS; do
            docker buildx build \
              --platform=linux/amd64,linux/arm64 \
              -t ghcr.io/${{ github.repository }}:$TAG \
              . --push
          done
